### ISSUE TITLE
Missing include for d9bc4796b0b_string_context_c

### ISSUE THREAD

**Issue by asottile** [jeff-hykin/cpp-textmate-grammar#476]
Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:

(in my text editor, this is the minimum to trigger this)

```cpp
#ifn
```

## It looks like:

sorry, don't have a vs code reproduction, here's the stacktrace it triggers:

```pytb
$ babi t.cpp
Traceback (most recent call last):
  File "/home/asottile/bin/babi", line 8, in <module>
    sys.exit(main())
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/main.py", line 146, in main
    return c_main(stdscr, filenames, positions, stdin, perf)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/main.py", line 56, in c_main
    res = _edit(screen, stdin)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/main.py", line 28, in _edit
    screen.draw()
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/screen.py", line 253, in draw
    self.file.draw(self.stdscr, self.margin)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/file.py", line 790, in draw
    file_hl.highlight_until(self.buf, self.buf.file_y + to_display)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/hl/syntax.py", line 119, in highlight_until
    state, regions = self._hl(state, lines[i], i == 0)  # type: ignore
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/hl/syntax.py", line 63, in _hl_uncached
    new_state, regions = highlight_line(
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 769, in highlight_line
    search_res = state.cur.rule.search(
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 480, in search
    return _do_regset(idx, match, self, compiler, state, pos)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 362, in _do_regset
    target_rule = compiler.compile_rule(rule.u_rules[idx])
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 650, in compile_rule
    ret = self._c_rules[rule] = self._compile_rule(grammar, rule)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 618, in _compile_rule
    regs, rules = self._patterns(grammar, rule.patterns)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 582, in _patterns
    tmp_regs, tmp_rules = self._include(
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 563, in _include
    return self._patterns(grammar, (repository[s[1:]],))
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 588, in _patterns
    tmp_regs, tmp_rules = self._patterns(grammar, rule.patterns)
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 582, in _patterns
    tmp_regs, tmp_rules = self._include(
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/highlight.py", line 563, in _include
    return self._patterns(grammar, (repository[s[1:]],))
  File "/home/asottile/opt/venv/lib/python3.8/site-packages/babi/fdict.py", line 44, in __getitem__
    raise KeyError(key)
KeyError: 'd9bc4796b0b_string_context_c'
```

## It should look like:

ideally it should not crash

I'm not sure where the `d9bc4796b0b` string comes from, I don't see it in the generator ruby files only in the output:

```console
$ git grep -l d9bc4796b0b
syntaxes/cpp.embedded.macro.tmLanguage.json
syntaxes/cpp.tmLanguage.json
```

The particular problematic code is this line:

https://github.com/jeff-hykin/cpp-textmate-grammar/blob/0e158ce0f26329776e608d6e80032d1b1decf7ec/syntaxes/cpp.tmLanguage.json#L12522

I do see a `string_context_c` include target, so perhaps it is supposed to go to that?

I believe the ruby source this is coming from is here, but I don't understand where the hex string comes from:

https://github.com/jeff-hykin/cpp-textmate-grammar/blob/0e158ce0f26329776e608d6e80032d1b1decf7ec/source/languages/cpp/lib/preprocessor.rb#L352

**Comment by matter123** [comment]
Thanks for catching that 😄

At one time there was both a `:string_context_c` and `:string_context`. `:string_context_c` was supposed to have been eliminated, but I guess I missed a couple of spots.

The hex string is coming from the deduplication code for exportable grammars. Exportable grammars have their keys prefixed unless they declare that their are using or exporting a name. The preprocessor exportable grammar did not declare that it was using `:string_context_c` and so it was prefixed.

**Comment by asottile** [comment]
brilliant!  thanks for the explanation I was really scratching my head!
